[package]
name = "nertboard-server"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nertboard-core.workspace = true

axum.workspace = true
tokio.workspace = true
uuid.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tower.workspace = true
tower-http.workspace = true

sqlx.workspace = true
dotenv.workspace = true

clap.workspace = true
thiserror.workspace = true
serde.workspace = true
rand.workspace = true
color-eyre.workspace = true

[dev-dependencies]
serde_json.workspace = true
http-body-util.workspace = true
